from ama_xiv_combat_sim.example_rotations.patch_70.healer.sch import add_sch_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.healer.whm import add_whm_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.healer.ast import add_ast_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.healer.sge import add_sge_rotations
