from ama_xiv_combat_sim.example_rotations.patch_655.healer.sch import add_sch_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.healer.whm import add_whm_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.healer.ast import add_ast_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.healer.sge import add_sge_rotations
