from ama_xiv_combat_sim.example_rotations.patch_655.melee.drg import add_drg_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.melee.mnk import add_mnk_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.melee.nin import add_nin_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.melee.rpr import add_rpr_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.melee.sam import add_sam_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.melee.vpr import add_vpr_rotations