from ama_xiv_combat_sim.example_rotations.specific_rotations import SpecificRotations


all_war_rotations = SpecificRotations()

ALL_WAR_ROTATIONS = {
    "WAR": {
        90: {
            "stats": {
                "wd": 132,
                "main_stat": 3330,
                "det_stat": 2182,
                "crit_stat": 2596,
                "dh_stat": 940,
                "speed_stat": 400,
                "tenacity": 601,
                "job_class": "WAR",
            },
            "skills": (
                "Tomahawk",
                "Infuriate",
                "Heavy Swing",
                "Maim",
                "Grade 8 Tincture",
                "Storm's Eye",
                "Inner Release",
                "Inner Chaos",
                "Upheaval",
                "Onslaught",
                "Primal Rend",
                "Inner Chaos",
                "Onslaught",
                "Fell Cleave",
                "Onslaught",
                "Fell Cleave",
                "Fell Cleave",
                "Heavy Swing",
                "Maim",
                "Storm's Path",
                "Fell Cleave",
                "Inner Chaos",
            ),
            "start_version": "6.55",
        },
        100: {
            "stats": {
                "wd": 146,
                "main_stat": 4839,
                "det_stat": 2525,
                "crit_stat": 3253,
                "dh_stat": 1176,
                "speed_stat": 420,
                "tenacity": 868,
                "job_class": "WAR",
            },
            "skills": (
                "Tomahawk",
                "Infuriate",
                "Heavy Swing",
                "Maim",
                "Storm's Eye",
                "Inner Release",
                "Grade 2 Gemdraught",
                "Inner Chaos",
                "Upheaval",
                "Onslaught",
                "Primal Rend",
                "Onslaught",
                "Primal Ruination",
                "Onslaught",
                "Fell Cleave",
                "Fell Cleave",
                "Fell Cleave",
                "Primal Wrath",
                "Infuriate",
                "Inner Chaos",
                "Heavy Swing",
                "Maim",
                "Storm's Path",
                "Fell Cleave",
                "Infuriate",
                "Inner Chaos",
            ),
            "start_version": "7.05",
        },
    },
    "WAR Party Buffs": {
        90: {
            "stats": {
                "wd": 132,
                "main_stat": 3330,
                "det_stat": 2182,
                "crit_stat": 2596,
                "dh_stat": 940,
                "speed_stat": 400,
                "tenacity": 601,
                "job_class": "WAR",
            },
            "party_skills": (
                (6.3, "Chain Stratagem", "SCH"),
                (7.1, "Battle Litany", "DRG"),
                (0.8, "Arcane Circle", "RPR"),
                (6.28, "Embolden", "RDM"),
            ),
            "skills": (
                "Tomahawk",
                "Infuriate",
                "Heavy Swing",
                "Maim",
                "Grade 8 Tincture",
                "Storm's Eye",
                "Inner Release",
                "Inner Chaos",
                "Upheaval",
                "Onslaught",
                "Primal Rend",
                "Inner Chaos",
                "Onslaught",
                "Fell Cleave",
                "Onslaught",
                "Fell Cleave",
                "Fell Cleave",
                "Heavy Swing",
                "Maim",
                "Storm's Path",
                "Fell Cleave",
                "Inner Chaos",
            ),
            "start_version": "6.55",
        }
    },
}

for k, v in ALL_WAR_ROTATIONS.items():
    all_war_rotations.add_rotation_data(k, v)
