from ama_xiv_combat_sim.simulator.game_data.patch_655.class_skills.ranged.brd import add_brd_skills
from ama_xiv_combat_sim.simulator.game_data.patch_655.class_skills.ranged.dnc import add_dnc_skills
from ama_xiv_combat_sim.simulator.game_data.patch_655.class_skills.ranged.mch import add_mch_skills
