from ama_xiv_combat_sim.example_rotations.patch_70.ranged.brd import add_brd_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.ranged.dnc import add_dnc_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.ranged.mch import add_mch_rotations

