from ama_xiv_combat_sim.example_rotations.patch_70.caster.blm import add_blm_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.caster.rdm import add_rdm_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.caster.smn import add_smn_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.caster.pct import add_pct_rotations
