from ama_xiv_combat_sim.example_rotations.patch_655.tank.war import add_war_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.tank.pld import add_pld_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.tank.drk import add_drk_rotations
from ama_xiv_combat_sim.example_rotations.patch_655.tank.gnb import add_gnb_rotations
