from ama_xiv_combat_sim.example_rotations.patch_70.tank.war import add_war_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.tank.pld import add_pld_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.tank.drk import add_drk_rotations
from ama_xiv_combat_sim.example_rotations.patch_70.tank.gnb import add_gnb_rotations
